// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package rabbitmq

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (DestinationConfig) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"caCert": {
			Default:     "",
			Description: "",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"clientCert": {
			Default:     "",
			Description: "clientCert, ClientKey, and CACert are the paths to the client certificate, client key, and CA certificate to use for TLS",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"clientKey": {
			Default:     "",
			Description: "",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"contentType": {
			Default:     "text/plain",
			Description: "contentType is the MIME content type of the messages written to rabbitmq",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"exchangeName": {
			Default:     "",
			Description: "exchangeName is the name of the exchange to publish to",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"exchangeType": {
			Default:     "direct",
			Description: "exchangeType is the type of the exchange to publish to",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"queueName": {
			Default:     "",
			Description: "queueName is the name of the queue to consume from / publish to",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"routingKey": {
			Default:     "",
			Description: "routingKey is the routing key to use when publishing to an exchange",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"url": {
			Default:     "",
			Description: "url is the RabbitMQ server url",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
	}
}
